// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: comunicacao.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

public static partial class TrocaArquivoRPC
{
  static readonly string __ServiceName = "TrocaArquivoRPC";

  static readonly grpc::Marshaller<global::PacoteConexao> __Marshaller_PacoteConexao = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::PacoteConexao.Parser.ParseFrom);
  static readonly grpc::Marshaller<global::RespostaConexao> __Marshaller_RespostaConexao = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::RespostaConexao.Parser.ParseFrom);
  static readonly grpc::Marshaller<global::Dispositivo> __Marshaller_Dispositivo = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Dispositivo.Parser.ParseFrom);
  static readonly grpc::Marshaller<global::Ambiente> __Marshaller_Ambiente = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Ambiente.Parser.ParseFrom);
  static readonly grpc::Marshaller<global::Arquivo> __Marshaller_Arquivo = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Arquivo.Parser.ParseFrom);
  static readonly grpc::Marshaller<global::JsonPacket> __Marshaller_JsonPacket = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::JsonPacket.Parser.ParseFrom);

  static readonly grpc::Method<global::PacoteConexao, global::RespostaConexao> __Method_Conectar = new grpc::Method<global::PacoteConexao, global::RespostaConexao>(
      grpc::MethodType.Unary,
      __ServiceName,
      "Conectar",
      __Marshaller_PacoteConexao,
      __Marshaller_RespostaConexao);

  static readonly grpc::Method<global::PacoteConexao, global::RespostaConexao> __Method_ConectarDevolta = new grpc::Method<global::PacoteConexao, global::RespostaConexao>(
      grpc::MethodType.Unary,
      __ServiceName,
      "ConectarDevolta",
      __Marshaller_PacoteConexao,
      __Marshaller_RespostaConexao);

  static readonly grpc::Method<global::Dispositivo, global::Dispositivo> __Method_AdicionarDispositivoEmAmbiente = new grpc::Method<global::Dispositivo, global::Dispositivo>(
      grpc::MethodType.Unary,
      __ServiceName,
      "AdicionarDispositivoEmAmbiente",
      __Marshaller_Dispositivo,
      __Marshaller_Dispositivo);

  static readonly grpc::Method<global::Ambiente, global::Ambiente> __Method_CriarAmbiente = new grpc::Method<global::Ambiente, global::Ambiente>(
      grpc::MethodType.Unary,
      __ServiceName,
      "CriarAmbiente",
      __Marshaller_Ambiente,
      __Marshaller_Ambiente);

  static readonly grpc::Method<global::Dispositivo, global::RespostaConexao> __Method_MoverDispositivo = new grpc::Method<global::Dispositivo, global::RespostaConexao>(
      grpc::MethodType.Unary,
      __ServiceName,
      "MoverDispositivo",
      __Marshaller_Dispositivo,
      __Marshaller_RespostaConexao);

  static readonly grpc::Method<global::Arquivo, global::RespostaConexao> __Method_MandarArquivo = new grpc::Method<global::Arquivo, global::RespostaConexao>(
      grpc::MethodType.Unary,
      __ServiceName,
      "MandarArquivo",
      __Marshaller_Arquivo,
      __Marshaller_RespostaConexao);

  static readonly grpc::Method<global::Arquivo, global::RespostaConexao> __Method_ReceberArquivo = new grpc::Method<global::Arquivo, global::RespostaConexao>(
      grpc::MethodType.Unary,
      __ServiceName,
      "ReceberArquivo",
      __Marshaller_Arquivo,
      __Marshaller_RespostaConexao);

  static readonly grpc::Method<global::Dispositivo, global::JsonPacket> __Method_RequisitarUsuarios = new grpc::Method<global::Dispositivo, global::JsonPacket>(
      grpc::MethodType.Unary,
      __ServiceName,
      "RequisitarUsuarios",
      __Marshaller_Dispositivo,
      __Marshaller_JsonPacket);

  static readonly grpc::Method<global::Dispositivo, global::JsonPacket> __Method_RequisitarAmbientes = new grpc::Method<global::Dispositivo, global::JsonPacket>(
      grpc::MethodType.Unary,
      __ServiceName,
      "RequisitarAmbientes",
      __Marshaller_Dispositivo,
      __Marshaller_JsonPacket);

  /// <summary>Service descriptor</summary>
  public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
  {
    get { return global::ComunicacaoReflection.Descriptor.Services[0]; }
  }

  /// <summary>Base class for server-side implementations of TrocaArquivoRPC</summary>
  [grpc::BindServiceMethod(typeof(TrocaArquivoRPC), "BindService")]
  public abstract partial class TrocaArquivoRPCBase
  {
    public virtual global::System.Threading.Tasks.Task<global::RespostaConexao> Conectar(global::PacoteConexao request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

    public virtual global::System.Threading.Tasks.Task<global::RespostaConexao> ConectarDevolta(global::PacoteConexao request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

    public virtual global::System.Threading.Tasks.Task<global::Dispositivo> AdicionarDispositivoEmAmbiente(global::Dispositivo request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

    public virtual global::System.Threading.Tasks.Task<global::Ambiente> CriarAmbiente(global::Ambiente request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

    public virtual global::System.Threading.Tasks.Task<global::RespostaConexao> MoverDispositivo(global::Dispositivo request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

    public virtual global::System.Threading.Tasks.Task<global::RespostaConexao> MandarArquivo(global::Arquivo request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

    public virtual global::System.Threading.Tasks.Task<global::RespostaConexao> ReceberArquivo(global::Arquivo request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

    public virtual global::System.Threading.Tasks.Task<global::JsonPacket> RequisitarUsuarios(global::Dispositivo request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

    public virtual global::System.Threading.Tasks.Task<global::JsonPacket> RequisitarAmbientes(global::Dispositivo request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

  }

  /// <summary>Client for TrocaArquivoRPC</summary>
  public partial class TrocaArquivoRPCClient : grpc::ClientBase<TrocaArquivoRPCClient>
  {
    /// <summary>Creates a new client for TrocaArquivoRPC</summary>
    /// <param name="channel">The channel to use to make remote calls.</param>
    public TrocaArquivoRPCClient(grpc::ChannelBase channel) : base(channel)
    {
    }
    /// <summary>Creates a new client for TrocaArquivoRPC that uses a custom <c>CallInvoker</c>.</summary>
    /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
    public TrocaArquivoRPCClient(grpc::CallInvoker callInvoker) : base(callInvoker)
    {
    }
    /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
    protected TrocaArquivoRPCClient() : base()
    {
    }
    /// <summary>Protected constructor to allow creation of configured clients.</summary>
    /// <param name="configuration">The client configuration.</param>
    protected TrocaArquivoRPCClient(ClientBaseConfiguration configuration) : base(configuration)
    {
    }

    public virtual global::RespostaConexao Conectar(global::PacoteConexao request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return Conectar(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual global::RespostaConexao Conectar(global::PacoteConexao request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_Conectar, null, options, request);
    }
    public virtual grpc::AsyncUnaryCall<global::RespostaConexao> ConectarAsync(global::PacoteConexao request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return ConectarAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual grpc::AsyncUnaryCall<global::RespostaConexao> ConectarAsync(global::PacoteConexao request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_Conectar, null, options, request);
    }
    public virtual global::RespostaConexao ConectarDevolta(global::PacoteConexao request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return ConectarDevolta(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual global::RespostaConexao ConectarDevolta(global::PacoteConexao request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_ConectarDevolta, null, options, request);
    }
    public virtual grpc::AsyncUnaryCall<global::RespostaConexao> ConectarDevoltaAsync(global::PacoteConexao request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return ConectarDevoltaAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual grpc::AsyncUnaryCall<global::RespostaConexao> ConectarDevoltaAsync(global::PacoteConexao request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_ConectarDevolta, null, options, request);
    }
    public virtual global::Dispositivo AdicionarDispositivoEmAmbiente(global::Dispositivo request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return AdicionarDispositivoEmAmbiente(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual global::Dispositivo AdicionarDispositivoEmAmbiente(global::Dispositivo request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_AdicionarDispositivoEmAmbiente, null, options, request);
    }
    public virtual grpc::AsyncUnaryCall<global::Dispositivo> AdicionarDispositivoEmAmbienteAsync(global::Dispositivo request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return AdicionarDispositivoEmAmbienteAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual grpc::AsyncUnaryCall<global::Dispositivo> AdicionarDispositivoEmAmbienteAsync(global::Dispositivo request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_AdicionarDispositivoEmAmbiente, null, options, request);
    }
    public virtual global::Ambiente CriarAmbiente(global::Ambiente request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return CriarAmbiente(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual global::Ambiente CriarAmbiente(global::Ambiente request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_CriarAmbiente, null, options, request);
    }
    public virtual grpc::AsyncUnaryCall<global::Ambiente> CriarAmbienteAsync(global::Ambiente request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return CriarAmbienteAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual grpc::AsyncUnaryCall<global::Ambiente> CriarAmbienteAsync(global::Ambiente request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_CriarAmbiente, null, options, request);
    }
    public virtual global::RespostaConexao MoverDispositivo(global::Dispositivo request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return MoverDispositivo(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual global::RespostaConexao MoverDispositivo(global::Dispositivo request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_MoverDispositivo, null, options, request);
    }
    public virtual grpc::AsyncUnaryCall<global::RespostaConexao> MoverDispositivoAsync(global::Dispositivo request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return MoverDispositivoAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual grpc::AsyncUnaryCall<global::RespostaConexao> MoverDispositivoAsync(global::Dispositivo request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_MoverDispositivo, null, options, request);
    }
    public virtual global::RespostaConexao MandarArquivo(global::Arquivo request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return MandarArquivo(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual global::RespostaConexao MandarArquivo(global::Arquivo request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_MandarArquivo, null, options, request);
    }
    public virtual grpc::AsyncUnaryCall<global::RespostaConexao> MandarArquivoAsync(global::Arquivo request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return MandarArquivoAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual grpc::AsyncUnaryCall<global::RespostaConexao> MandarArquivoAsync(global::Arquivo request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_MandarArquivo, null, options, request);
    }
    public virtual global::RespostaConexao ReceberArquivo(global::Arquivo request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return ReceberArquivo(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual global::RespostaConexao ReceberArquivo(global::Arquivo request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_ReceberArquivo, null, options, request);
    }
    public virtual grpc::AsyncUnaryCall<global::RespostaConexao> ReceberArquivoAsync(global::Arquivo request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return ReceberArquivoAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual grpc::AsyncUnaryCall<global::RespostaConexao> ReceberArquivoAsync(global::Arquivo request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_ReceberArquivo, null, options, request);
    }
    public virtual global::JsonPacket RequisitarUsuarios(global::Dispositivo request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return RequisitarUsuarios(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual global::JsonPacket RequisitarUsuarios(global::Dispositivo request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_RequisitarUsuarios, null, options, request);
    }
    public virtual grpc::AsyncUnaryCall<global::JsonPacket> RequisitarUsuariosAsync(global::Dispositivo request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return RequisitarUsuariosAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual grpc::AsyncUnaryCall<global::JsonPacket> RequisitarUsuariosAsync(global::Dispositivo request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_RequisitarUsuarios, null, options, request);
    }
    public virtual global::JsonPacket RequisitarAmbientes(global::Dispositivo request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return RequisitarAmbientes(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual global::JsonPacket RequisitarAmbientes(global::Dispositivo request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_RequisitarAmbientes, null, options, request);
    }
    public virtual grpc::AsyncUnaryCall<global::JsonPacket> RequisitarAmbientesAsync(global::Dispositivo request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return RequisitarAmbientesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual grpc::AsyncUnaryCall<global::JsonPacket> RequisitarAmbientesAsync(global::Dispositivo request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_RequisitarAmbientes, null, options, request);
    }
    /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
    protected override TrocaArquivoRPCClient NewInstance(ClientBaseConfiguration configuration)
    {
      return new TrocaArquivoRPCClient(configuration);
    }
  }

  /// <summary>Creates service definition that can be registered with a server</summary>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static grpc::ServerServiceDefinition BindService(TrocaArquivoRPCBase serviceImpl)
  {
    return grpc::ServerServiceDefinition.CreateBuilder()
        .AddMethod(__Method_Conectar, serviceImpl.Conectar)
        .AddMethod(__Method_ConectarDevolta, serviceImpl.ConectarDevolta)
        .AddMethod(__Method_AdicionarDispositivoEmAmbiente, serviceImpl.AdicionarDispositivoEmAmbiente)
        .AddMethod(__Method_CriarAmbiente, serviceImpl.CriarAmbiente)
        .AddMethod(__Method_MoverDispositivo, serviceImpl.MoverDispositivo)
        .AddMethod(__Method_MandarArquivo, serviceImpl.MandarArquivo)
        .AddMethod(__Method_ReceberArquivo, serviceImpl.ReceberArquivo)
        .AddMethod(__Method_RequisitarUsuarios, serviceImpl.RequisitarUsuarios)
        .AddMethod(__Method_RequisitarAmbientes, serviceImpl.RequisitarAmbientes).Build();
  }

  /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
  /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
  /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static void BindService(grpc::ServiceBinderBase serviceBinder, TrocaArquivoRPCBase serviceImpl)
  {
    serviceBinder.AddMethod(__Method_Conectar, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::PacoteConexao, global::RespostaConexao>(serviceImpl.Conectar));
    serviceBinder.AddMethod(__Method_ConectarDevolta, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::PacoteConexao, global::RespostaConexao>(serviceImpl.ConectarDevolta));
    serviceBinder.AddMethod(__Method_AdicionarDispositivoEmAmbiente, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Dispositivo, global::Dispositivo>(serviceImpl.AdicionarDispositivoEmAmbiente));
    serviceBinder.AddMethod(__Method_CriarAmbiente, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ambiente, global::Ambiente>(serviceImpl.CriarAmbiente));
    serviceBinder.AddMethod(__Method_MoverDispositivo, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Dispositivo, global::RespostaConexao>(serviceImpl.MoverDispositivo));
    serviceBinder.AddMethod(__Method_MandarArquivo, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Arquivo, global::RespostaConexao>(serviceImpl.MandarArquivo));
    serviceBinder.AddMethod(__Method_ReceberArquivo, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Arquivo, global::RespostaConexao>(serviceImpl.ReceberArquivo));
    serviceBinder.AddMethod(__Method_RequisitarUsuarios, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Dispositivo, global::JsonPacket>(serviceImpl.RequisitarUsuarios));
    serviceBinder.AddMethod(__Method_RequisitarAmbientes, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Dispositivo, global::JsonPacket>(serviceImpl.RequisitarAmbientes));
  }

}
#endregion
